start-at-login = true
key-mapping.preset = "qwerty"

default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]

inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-q = "workspace q"
alt-w = "workspace w"
alt-e = "workspace e"
alt-r = "workspace r"
alt-t = "workspace t"

alt-shift-1 = ["move-node-to-workspace 1", "workspace 1"]
alt-shift-2 = ["move-node-to-workspace 2", "workspace 2"]
alt-shift-3 = ["move-node-to-workspace 3", "workspace 3"]
alt-shift-4 = ["move-node-to-workspace 4", "workspace 4"]
alt-shift-5 = ["move-node-to-workspace 5", "workspace 5"]
alt-shift-q = ["move-node-to-workspace q", "workspace q"]
alt-shift-w = ["move-node-to-workspace w", "workspace w"]
alt-shift-e = ["move-node-to-workspace e", "workspace e"]
alt-shift-r = ["move-node-to-workspace r", "workspace r"]
alt-shift-t = ["move-node-to-workspace t", "workspace t"]

alt-d = "focus-monitor --wrap-around next"
alt-shift-d = "move-workspace-to-monitor --wrap-around next"

alt-h = "focus left --boundaries-action stop"
alt-j = "focus down --boundaries-action stop"
alt-k = "focus up --boundaries-action stop"
alt-l = "focus right --boundaries-action stop"

alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-shift-minus = "resize smart -50"
alt-shift-equal = "resize smart +50"

alt-space = "layout h_tiles v_tiles"
alt-f = "fullscreen"

alt-backtick = ["reload-config", "mode inactive"]

[mode.inactive.binding]

alt-backtick = ["reload-config", "mode main"]
