start-at-login = true
key-mapping.preset = "qwerty"

default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]

inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

ctrl-1 = "workspace 1"
ctrl-2 = "workspace 2"
ctrl-3 = "workspace 3"
ctrl-4 = "workspace 4"
ctrl-5 = "workspace 5"
ctrl-q = "workspace q"
ctrl-w = "workspace w"
ctrl-e = "workspace e"
ctrl-r = "workspace r"
ctrl-t = "workspace t"

ctrl-shift-1 = ["move-node-to-workspace 1", "workspace 1"]
ctrl-shift-2 = ["move-node-to-workspace 2", "workspace 2"]
ctrl-shift-3 = ["move-node-to-workspace 3", "workspace 3"]
ctrl-shift-4 = ["move-node-to-workspace 4", "workspace 4"]
ctrl-shift-5 = ["move-node-to-workspace 5", "workspace 5"]
ctrl-shift-q = ["move-node-to-workspace q", "workspace q"]
ctrl-shift-w = ["move-node-to-workspace w", "workspace w"]
ctrl-shift-e = ["move-node-to-workspace e", "workspace e"]
ctrl-shift-r = ["move-node-to-workspace r", "workspace r"]
ctrl-shift-t = ["move-node-to-workspace t", "workspace t"]

ctrl-d = "focus-monitor --wrap-around next"
ctrl-shift-d = "move-workspace-to-monitor --wrap-around next"

ctrl-h = "focus left --boundaries-action stop"
ctrl-j = "focus down --boundaries-action stop"
ctrl-k = "focus up --boundaries-action stop"
ctrl-l = "focus right --boundaries-action stop"

ctrl-shift-h = "move left"
ctrl-shift-j = "move down"
ctrl-shift-k = "move up"
ctrl-shift-l = "move right"

ctrl-shift-minus = "resize smart -50"
ctrl-shift-equal = "resize smart +50"

ctrl-space = "layout h_tiles v_tiles"
ctrl-f = "fullscreen"
