contexts:
  default:
    defaultIde: none
    defaultProvider: kubernetes
    options:
      DOTFILES_URL:
        userProvided: true
        value: git@github.com:franco-ruggeri/dotfiles.git
      GPG_AGENT_FORWARDING:
        userProvided: true
        value: "true"
    providers:
      docker:
        creationTimestamp: "2025-05-17T16:39:46Z"
        initialized: true
        options:
          DOCKER_BUILDER: {}
          DOCKER_HOST: {}
          DOCKER_PATH:
            value: docker
          INACTIVITY_TIMEOUT: {}
      kubernetes:
        creationTimestamp: "2025-05-19T13:55:28Z"
        initialized: true
        options:
          ARCHITECTURE: {}
          CLUSTER_ROLE: {}
          CREATE_NAMESPACE:
            value: "true"
          DISK_SIZE:
            value: 10Gi
          DOCKERLESS_DISABLED:
            value: "false"
          DOCKERLESS_IMAGE: {}
          INACTIVITY_TIMEOUT: {}
          KUBERNETES_CONFIG: {}
          KUBERNETES_CONTEXT: {}
          KUBERNETES_NAMESPACE:
            value: default
          KUBERNETES_PULL_SECRETS_ENABLED:
            value: "true"
          LABELS: {}
          NODE_SELECTOR: {}
          POD_MANIFEST_TEMPLATE: {}
          POD_TIMEOUT:
            value: 10m
          PVC_ACCESS_MODE: {}
          PVC_ANNOTATIONS: {}
          RESOURCES: {}
          SERVICE_ACCOUNT: {}
          STORAGE_CLASS: {}
          STRICT_SECURITY:
            value: "false"
          WORKSPACE_VOLUME_MOUNT: {}
defaultContext: default
